spring:
  application:
    name: twitter-to-kafka-service
  config:
    import:
      - "optional:configserver:"
      - "optional:classpath:application-logging.yaml"
  cloud:
    config:
      uri: http://localhost:8888
      name: twitter-to-kafka-service
      enabled: true
      fail-fast: true
      retry:
        initial-interval: 2000
        max-attempts: 6
        max-interval: 2000