spring:
  application:
    name: ai-generated-tweet-to-kafka
  ai:
    openai:
      api-key: ${DEEPSEEK_AI_KEY:sk-3f1fae00542a484382462adb41169a38}
#      api-key: ${OPEN_AI_KEY:}
      base-url: "https://api.deepseek.com"
#      base-url: "https://api.openai.com"
      chat:
        options:
          model: "deepseek-chat"
#          model: "gpt-4o-mini"
          temperature: 1
          maxTokens: 150
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: deepseek-r1:14b
          temperature: 1
          max-tokens: 150


ai-generated-tweet-to-kafka:
  streaming-data-keywords:
    - Java
    - Microservices
    - Spring
    - kafka
    - ElasticSearch
#  ai-service: OpenAI-JavaClient
#  ai-service: Google-GenAI
  ai-service: SpringAI-OpenAI
  scheduler-duration: PT30S
  prompt: "Generate a json with 4 elements called createdAt, id, text and user. 
          The user element has also a nested json element called id. 
          For createdAt use a date in format 'EEE MMM dd HH:mm:ss zzz yyyy', example date would be 
          'Fri May 08 23:30:25 UTC 2026', for id use a java long value, for text use a string including one or more of the keyword {keywords}.
          For id field of the user field use a  jav long value.Do not write anything in the response other than json text.
          That means omit ```json part in the response and any other explanation. Do not use new lines in the response.
          Do not include the L letter in th end of the long values. Only give 1 result in the response"
  keywords-placeholder: "{keywords}"
  open-ai:
    url: "https://api.openai.com/v1/chat/completions"
    api-key: ${OPEN_AI_KEY}
    content-type: "application/json"
    model: "gpt-4o-mini"
    max-completion-tokens: 150
    temperature: 1
    messages:
      - role: "user"
        content:
          -
            type: "text"
  google-gen-ai:
    projectId: "microservices-demo"
    location: "us-central1"
    modelName: "gemini-3-flash-preview"
    max-output-tokens: 150
    temperature: 1
    candidate-count: 1
